import Vue from 'vue'
import { Radio, RadioGroup, Checkbox, CheckboxGroup, Switch, TimePicker, DatePicker, Col, Option, Select, Form, FormItem, Button, Breadcrumb, BreadcrumbItem, Menu, MenuItem, Submenu, Dropdown, DropdownMenu, DropdownItem, scrollbar, Table, TableColumn, Tag, Loading, Input, Tree, Alert } from 'element-ui'

Vue.use(Button)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(Submenu)
Vue.use(Dropdown)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(scrollbar)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Tag)
Vue.use(Loading)
Vue.use(Input)
Vue.use(Tree)
Vue.use(Alert)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Select)
Vue.use(Option)
Vue.use(Col)
Vue.use(DatePicker)
Vue.use(TimePicker)
Vue.use(Switch)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(Radio)
Vue.use(RadioGroup)
